export const OPENAI_PROMPTS = [
  "Advocate privacy in tech",
  "Tech",
  "Future of NFTs",
  "Benefits of Kiwi",
  "Software Development Jobs",
  "AI in the future",
  "Web 3.0 future",
  "Android vs IoS",
  "Quote a random movie/TV show",
  "Future of Dogecoin",
  "What are your thoughts on terminator?",
  "What is the future of Docker",
  "What is the prospect of Kubernetes",
  "What is the future of electric cars?",
  "Fun facts about the James Webb Telescope",
  "Fun astronomy facts",
];